# rmd_generator.R
# Generate R Markdown document from converted SPSS syntax

#' Generate R Markdown document
#'
#' Creates a complete R Markdown document from parsed and converted SPSS
#' syntax, including data loading, transformations, and analyses.
#'
#' @param sav_data SAV data info from parse_sav()
#' @param sav_path Original SAV file path
#' @param parsed_syntax Parsed SPSS syntax
#' @param converted_code Converted R code blocks
#' @param output_dir Output directory
#' @param options Rendering options
#' @param base_name Optional base name for output files
#' @return List with rmd_path and data_path
#' @examples
#' \dontrun{
#' parsed    <- parse_sps("analysis.sps")
#' sav_info  <- parse_sav("data.sav")
#' converted <- convert_all_commands(parsed, sav_info)
#' rmd <- generate_rmd(
#'   sav_data       = sav_info,
#'   sav_path       = "data.sav",
#'   parsed_syntax  = parsed,
#'   converted_code = converted,
#'   output_dir     = tempdir()
#' )
#' rmd$rmd_path
#' }
#' @export
generate_rmd <- function(sav_data, sav_path, parsed_syntax, converted_code,
                         output_dir, options = list(), base_name = NULL) {
  include_original <- options$include_original %||% TRUE
  include_effect_sizes <- options$include_effect_sizes %||% TRUE
  table_style <- options$table_style %||% "apa7"

  if (is.null(base_name)) {
    base_name <- tools::file_path_sans_ext(basename(sav_path))
  }

  # ---- YAML header ----
  yaml_header <- glue::glue('---
title: "SPSS to R Conversion: {base_name}"
author: "Generated by SPSS2R"
date: "`r format(Sys.Date(), \'%B %d, %Y\')`"
output:
  html_document:
    theme: lumen
    highlight: tango
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    code_folding: hide
    self_contained: true
    df_print: paged
---
')

  # ---- Setup chunk ----
  setup_chunk <- '```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  error = TRUE,
  fig.width = 10,
  fig.height = 7
)

library(haven)
library(dplyr)
library(jmv)

options(jmv.progress = FALSE)
```
'

  # ---- Data loading ----
  data_rds_name <- paste0(base_name, ".rds")
  data_section <- glue::glue('
## Data Overview

```{{r load-data}}
# Load dataset
data <- readRDS("{data_rds_name}")

# Normalize variable names to UPPERCASE (SPSS is case-insensitive)
normalize_spss_names <- function(x) {{
  if (is.null(x)) return(x)
  x <- toupper(x)
  x <- gsub("[^A-Z0-9_]", ".", x)
  x <- ifelse(grepl("^[0-9.]", x), paste0("X", x), x)
  x
}}

names(data) <- normalize_spss_names(names(data))

# Convert haven_labelled to native R types for jmv compatibility
clean_data <- function(d) {{
  d[] <- lapply(d, function(x) {{
    if (inherits(x, "haven_labelled")) x <- tryCatch(as.numeric(x), error = function(e) x)
    if (is.logical(x)) x <- as.numeric(x)
    x
  }})
  d
}}

data <- clean_data(data)

cat("**Variables:**", ncol(data), "\\n\\n")
cat("**Observations:**", nrow(data), "\\n\\n")

# Warn about empty columns
na_cols <- colSums(is.na(data)) == nrow(data)
if (any(na_cols)) {{
  cat("**Warning:** The following variables are entirely NA:\\n\\n")
  cat(paste(names(data)[na_cols], collapse = ", "), "\\n\\n")
}}
```

---

')

  # ---- Separate transformations from analyses ----
  # Filter out skipped commands (metadata) and empty results
  converted_code <- converted_code[!sapply(converted_code, function(x) {
    isTRUE(x$skip) || is.null(x$r_code) || nchar(trimws(x$r_code)) == 0
  })]

  transformations <- converted_code[sapply(converted_code, function(x) isTRUE(x$is_transformation))]
  analyses <- converted_code[!sapply(converted_code, function(x) isTRUE(x$is_transformation))]

  # Filter out pure EXECUTE from transformations (they add noise)
  transformations <- transformations[!sapply(transformations, function(x) {
    identical(trimws(x$analysis_type), "EXECUTE")
  })]

  # ---- Data transformations section ----
  transform_section <- ""
  if (length(transformations) > 0) {
    transform_chunks <- lapply(seq_along(transformations), function(i) {
      conv <- transformations[[i]]
      orig_idx <- conv$order
      orig <- if (!is.null(orig_idx) && orig_idx <= length(parsed_syntax)) {
        parsed_syntax[[orig_idx]]$raw
      } else {
        ""
      }

      orig_comment <- if (include_original && nchar(orig) > 0) {
        glue::glue("
### Original SPSS Syntax
```spss
{orig}
```
")
      } else {
        ""
      }

      glue::glue('
## Transformation {i}: {conv$analysis_type}

{orig_comment}

```{{r transform-{i}}}
tryCatch({{
{conv$r_code}
}}, error = function(e) {{
  cat("**Transformation failed:**", e$message, "\\n")
}})
```
')
    })

    transform_section <- glue::glue('
# Data Transformations

These transformations are executed first to prepare the data for analysis.

{paste(transform_chunks, collapse = "\\n\\n---\\n\\n")}

---

## Final Data Cleanup

```{{r final-cleanup}}
data <- clean_data(data)
```

---

')
  }

  # ---- Analysis sections ----
  # Filter out unsupported/error analyses that are just noise
  meaningful_analyses <- analyses[!sapply(analyses, function(x) {
    grepl("^Unsupported:", x$analysis_type) ||
    grepl("^Error:", x$analysis_type) ||
    identical(trimws(x$analysis_type), "EXECUTE") ||
    identical(trimws(x$analysis_type), "Split File")
  })]

  analysis_sections <- lapply(seq_along(meaningful_analyses), function(i) {
    conv <- meaningful_analyses[[i]]
    orig_idx <- conv$order
    orig <- if (!is.null(orig_idx) && orig_idx <= length(parsed_syntax)) {
      parsed_syntax[[orig_idx]]$raw
    } else {
      ""
    }

    orig_comment <- if (include_original && nchar(orig) > 0) {
      glue::glue("
### Original SPSS Syntax
```spss
{orig}
```
")
    } else {
      ""
    }

    glue::glue('
## Analysis {i}: {conv$analysis_type}

{orig_comment}

### R Code
```{{r analysis-{i}}}
tryCatch({{
  results <- {conv$r_code}
  results
}}, error = function(e) {{
  cat("**Analysis error:**", e$message, "\\n")
}})
```
')
  })

  # ---- Unsupported commands summary ----
  unsupported <- analyses[sapply(analyses, function(x) {
    grepl("^Unsupported:", x$analysis_type)
  })]

  unsupported_section <- ""
  if (length(unsupported) > 0) {
    cmds <- sapply(unsupported, function(x) x$analysis_type)
    unsupported_section <- glue::glue('
---

## Unsupported Commands

The following SPSS commands were not automatically converted and may need manual attention:

{paste("- ", cmds, collapse = "\\n")}
')
  }

  # ---- Footer ----
  footer <- '
---

# Session Info

```{r session-info}
sessionInfo()
```

---

*Report generated by [SPSS2R](https://github.com/your-repo/SPSS2R)*
'

  # ---- Combine all sections ----
  full_rmd <- paste(c(
    yaml_header,
    setup_chunk,
    data_section,
    transform_section,
    "# Analyses\n\n",
    paste(analysis_sections, collapse = "\n\n---\n\n"),
    unsupported_section,
    footer
  ), collapse = "\n")

  # Write RMD file
  rmd_path <- file.path(output_dir, paste0(base_name, ".Rmd"))
  writeLines(full_rmd, rmd_path, useBytes = TRUE)

  data_path <- file.path(output_dir, data_rds_name)

  list(
    rmd_path = rmd_path,
    data_path = data_path
  )
}
